### ISSUE TITLE
Can't compile to release mode.

### ISSUE THREAD

**Issue by shove70** [shove70/crypto#18]
@DarkRiDDeR:

cmd-line:
dub build -b release
result:
Long time no response

This problem is related to the implementation of blake2

**Comment by DarkRiDDeR** [comment]
what platform and compiler?

**Comment by shove70** [comment]
dmd 2.087.1
macos, windows.

ldc2 1.17.0 can compile normally.

**Comment by shove70** [comment]
$ dmd -lib -of.dub/build/library-release-linux.posix-x86_64-dmd_2087-7976112B6E4AE82C2341CDBCA9E3706B/libcrypto.a -release -inline -O -w -version=Have_crypto -version=Have_intel_intrinsics -version=Have_zero_memory -Isrc -I../../intel-intrinsics-1.1.1/intel-intrinsics/source -I../../zero-memory-0.1.3/zero-memory/src/ src/crypto/aes.d src/crypto/base58.d src/crypto/bigint.d src/crypto/blake2/blake2b.d src/crypto/blake2/blake2b_round.d src/crypto/blake2/blake2s.d src/crypto/blake2/blake2s_round.d src/crypto/blake2/impl.d src/crypto/hex.d src/crypto/padding.d src/crypto/random.d src/crypto/rsa.d src/crypto/tea.d -vcolumns

Long time no response.

If blake2 is not compiled, it will pass smoothly:

$ dmd -lib -of.dub/build/library-release-linux.posix-x86_64-dmd_2087-7976112B6E4AE82C2341CDBCA9E3706B/libcrypto.a -release -inline -O -w -version=Have_crypto -version=Have_intel_intrinsics -version=Have_zero_memory -Isrc -I../../intel-intrinsics-1.1.1/intel-intrinsics/source -I../../zero-memory-0.1.3/zero-memory/src/ src/crypto/aes.d src/crypto/base58.d src/crypto/bigint.d  src/crypto/hex.d src/crypto/padding.d src/crypto/random.d src/crypto/rsa.d src/crypto/tea.d -vcolumns
OK.

**Comment by DarkRiDDeR** [comment]
Oh, this problem is due to mixin templates. DMD processes them for a very long time.  It chokes on a few steps. Hmm... And yes, LDC normally compiles the release. While you can use it. I'll try to come up with something on the weekend.

**Comment by shove70** [comment]
OK

**Comment by DarkRiDDeR** [comment]
Please compile this solution too. It seems to work for me

**Comment by shove70** [comment]
ok, use LDC.

**Comment by DarkRiDDeR** [comment]
Let the question be better open so far. Maybe someone has the same problem. I will soon make a pull request. But this is not a complete solution to the problem. Maybe someone will offer a better way out of this situation, or a new version of DMD will decide this.
