### ISSUE TITLE
Error when compiling the library

### ISSUE THREAD

**Issue by Billy02357** [shove70/crypto#26]
Hello,
my issue is that when I try to compile my program which imports the crypto library, it will show this error message:
`Performing "debug" build using /usr/bin/gdc for x86_64.
intel-intrinsics 1.3.10: target for configuration "library" is up to date.
crypto 0.2.16: building configuration "library"...
/home/anon/.dub/packages/crypto-0.2.16/crypto/src/crypto/bigint.d:73:31: error: no property 'getDigit' for type 'const(BigInt)'
   73 |             uint digit = value.getDigit!uint(i);
      |                               ^
/home/anon/.dub/packages/crypto-0.2.16/crypto/src/crypto/bigint.d:209:30: error: no property 'getDigit' for type 'const(BigInt)'
  209 |                 arr[i] = data.getDigit!uint(i);
      |                              ^
/home/anon/.dub/packages/crypto-0.2.16/crypto/src/crypto/bigint.d:330:29: error: no property 'getDigit' for type 'const(BigInt)'
  330 |         int u = cast(int) (n.getDigit!uint(0));
      |                             ^
/home/anon/.dub/packages/crypto-0.2.16/crypto/src/crypto/bigint.d:390:37: error: no property 'getDigit' for type 'const(BigInt)'
  390 |             int digit = cast(int) (n.getDigit!uint(m >>> 5));
      |                                     ^
/home/anon/.dub/packages/crypto-0.2.16/crypto/src/crypto/utils.d:81:30: error: pure function 'crypto.utils.secureZeroMemory' cannot call impure function 'core.bitop.volatileStore'
   81 |                 volatileStore(cast(size_t*) p, size_t(0));
      |                              ^
/home/anon/.dub/packages/crypto-0.2.16/crypto/src/crypto/utils.d:83:30: error: pure function 'crypto.utils.secureZeroMemory' cannot call impure function 'core.bitop.volatileStore'
   83 |                 volatileStore(cast(ubyte*) p, ubyte(0));
      |                              ^
/usr/bin/gdc failed with exit code 1.`

Please tell me what I'm doing wrong

**Comment by DarkRiDDeR** [comment]
Hello. You can use the DMD or LDC compiler as a temporary solution. This should fix the problem

**Comment by shove70** [comment]
Is your GDC version too old? Try compiling with a newer version of DMD, ldc2 or GDC.

The Bigint.getDigit() method was added to the Phobos library on Jan 4, 2018:
https://github.com/dlang/phobos/commit/dae55d039c8392246514caf6ada93cbb82320511

**Comment by Billy02357** [comment]
> Hello. You can use the DMD or LDC compiler as a temporary solution. This should fix the problem. Please also tell your compiler version



> Is your GDC version too old? Try compiling with a newer version of DMD, ldc2 or GDC.
> 
> The Bigint.getDigit() method was added to the Phobos library on Jan 4, 2018:
> [dlang/phobos@dae55d0](https://github.com/dlang/phobos/commit/dae55d039c8392246514caf6ada93cbb82320511)

my gdc version is 11.1.0, latest that pacman offers.

I tried with dmd and it gives me a different error:

```
Fetching intel-intrinsics 1.3.10 (getting selected version)...
Fetching crypto 0.2.16 (getting selected version)...
Performing "debug" build using /usr/bin/dmd for x86_64.
intel-intrinsics 1.3.10: building configuration "library"...
crypto 0.2.16: building configuration "library"...
pw ~master: building configuration "application"...
source/main.d(2,8): Error: module `crypto` is in file 'crypto.d' which cannot be read
import path[0] = source/
import path[1] = /home/anon/.dub/packages/crypto-0.2.16/crypto/src
import path[2] = /home/anon/.dub/packages/intel-intrinsics-1.3.10/intel-intrinsics/source
import path[3] = /usr/include/dlang/dmd
/usr/bin/dmd failed with exit code 1.
```

**Comment by Billy02357** [comment]
Ok, I think i found my error:
In the source file i wrote "import crypto;" and it couldn't find any modules because I needed to specify for example "import crypto.aes;".
I tried with this fix and only compiled with dmd but not gdc. Is gdc deprecated or something?
I've heard gdc offers longer compile times but faster binaries, and dmd the reverse.

**Comment by shove70** [comment]
GDC has not been an independent component for several years, and now it is part of GCC. If you have GDC installed in the latest version of GCC (such as 11.1.0), it is the latest.

crypto hasn't tried to compile in GDC. I've tried it in recent days.

In addition: ldc2 is a good choice, whether it is compiled or run very fast
