### ISSUE TITLE
Doc mistake: should use keyPair.privateKey to RSA.decrypt

### ISSUE THREAD

**Issue by mingwugmail** [shove70/crypto#27]
On readme.md

```
ubyte[] en = RSA.encrypt(keyPair.privateKey, cast(ubyte[])data);
ubyte[] de = RSA.decrypt(keyPair.publicKey, en);
```
should be:

```
ubyte[] en = RSA.encrypt(keyPair.publicKey, cast(ubyte[])data);
ubyte[] de = RSA.decrypt(keyPair.privateKey, en);
```

**Comment by shove70** [comment]
Public key and private key are a pair of keys with exactly the same characteristics. Encryption with public key is decrypted with private key, otherwise encryption with private key is decrypted with public key.

The names of public key and private key are for use scenarios, they are not absolute.

**Comment by mingwugmail** [comment]
While it is possible to use the key pair interchangeably, as a demo, it's better to follow the correct concept, eps. as a tutorial.

For example, are you going to *publish* your *private* key for others to send you message?

BTW, check:
https://cs.stackexchange.com/questions/59675/can-a-public-key-be-used-to-decrypt-a-message-encrypted-by-the-corresponding-pri

Why not just fix the small typo in the doc?
