### ISSUE TITLE
Non-deterministic failure in RSA

### ISSUE THREAD

**Issue by Boris-Barboris** [shove70/crypto#6]
The following code randomly fails on both 64bit linux and 32bit windows. Try running the binary 10-15 times.

```d
import crypto;

unittest
{
	import std.stdio;
	import std.conv: to;

	RSAKeyPair pair = RSA.generateKeyPair(2048);
	for(int i = 0; i < 256; i++)
	{
		string data = "123test";
		ubyte[] en = RSA.encrypt(RSA.decodeKey(pair.publicKey), cast(ubyte[]) data);
		ubyte[] de = RSA.decrypt(RSA.decodeKey(pair.privateKey), en);
		if (!(cast(string) de == data))
		{
			writeln("crashed on iteration ", i);
			writeln(cast(string) de);
			assert(0);
		}
	}
}
```

Example output:
```
crashed on iteration 9
▼g��.���t‼ʵΏ,7�ճ=�"\�������♀�7��v���S3�"�►}]W&U=�aٕ�{�]x��
�t� �'�����~��T�$(�@�pVq�%�m����
ͰS���5~∟�6��q��♫>���Z1ۻ��񼓎��=A�q�����→�B→=�m~j�
�d�1�܃��☻��☼�↔�������)��☼�↨Ք0���YL9�R�v L���pj}E◄�vG���A���♦�� _� ↔E���ԛ�♥

core.exception.AssertError@xxxxxx\encryption.d(43): unittest failure
```

Compiler is DMD32 D Compiler v2.083.0 on windows, DMD64 D Compiler v2.083.0 on Linux.

**Comment by Boris-Barboris** [comment]
Reproduced on
```
LDC - the LLVM D compiler (1.14.0):
  based on DMD v2.084.1 and LLVM 7.0.1
```

**Comment by shove70** [comment]
Oh, as you said, I saw the problem and I'll fix it.
Thanks.

**Comment by shove70** [comment]
Fix: #6.

**Comment by Boris-Barboris** [comment]
Sorry, do you understand wich part of old iterative powMod was wrong? When I tried to fix it, I didn't find anything wrong with it...
Maybe it's the BigInt's bug?

**Comment by shove70** [comment]
Hello, I don't see where the problem is. When I changed powMod and compiled it with DMD 2.085.0, it never happened again.

I'll think about it again...

**Comment by shove70** [comment]
> Sorry, do you understand wich part of old iterative powMod was wrong? When I tried to fix it, I didn't find anything wrong with it...
> Maybe it's the BigInt's bug?

I also suspect that BigInt may have BUG now.

**Comment by shove70** [comment]
```
    static BigInt powMod(in BigInt base, in BigInt modulus, in BigInt exponent)
    {
        assert(base >= 1 && exponent >= 0 && modulus >= 1);

        BigInt result = BigInt("1");
        BigInt b = base;
        BigInt e = exponent;

        while (e > 0)
        {
            if (e & 1)
            {
                result = (result * b) % modulus;
            }

            b = (b * b) % modulus;
            e >>= 1;
        }

        return result;
    }
```

```
    static BigInt powMod(in BigInt base, in BigInt modulus, in BigInt exponent)
    {
        assert(base >= 1 && exponent >= 0 && modulus >= 1);

        if (exponent == 0)
        {
            return BigInt(1) % modulus;
        }

        if (exponent == 1)
        {
            return base % modulus;
        }

        BigInt temp = powMod(base, modulus, exponent / 2);

        return (exponent % 2 != 0) ? (temp * temp * base) % modulus : (temp * temp) % modulus;
    }
```

It's really strange. What's the first problem with powMod? Why does the second powMod work?

**Comment by shove70** [comment]
I don't see what's wrong, but there must be a problem.
I tested with two powMods and found that their results were inconsistent, and powMod2 was correct.

```
    static BigInt powMod_1(BigInt base, BigInt modulus, BigInt exponent)
    {
        assert(base >= 1 && exponent >= 0 && modulus >= 1);

        BigInt result = BigInt("1");

        while (exponent > 0)
        {
            if (exponent & 1)
            {
                result = (result * base) % modulus;
            }

            base = ((base % modulus) * (base % modulus)) % modulus;
            exponent >>= 1;
        }

        return result;
    }
```

```
    static BigInt powMod_2(BigInt base, BigInt modulus, BigInt exponent)
    {
        assert(base >= 1 && exponent >= 0 && modulus >= 1);

        if (exponent == 0)
        {
            return BigInt(1) % modulus;
        }

        if (exponent == 1)
        {
            return base % modulus;
        }

        BigInt temp = powMod(base, modulus, exponent / 2);

        return (exponent & 1) ? (temp * temp * base) % modulus : (temp * temp) % modulus;
    }
```

test:
base = 16298863723008062324
modulus = 15592449738095488747095865752434291846961185542216220364759273981537092410281077438681696466616075686558177072453373402338707270142067490009719653528419587472581511984462717336534941668232441962559088176638497609044546648097927645721037778102973426356054296888813806902955798744299849144156358264329743948114764184416762788718214428905372552136684197402848523489807177325912904135652219542981709775375540339611246490836320016382720250825185957794383439798883449063066374895720135846683755238373327764428067892090073454994927125784245547852359595514868496354506574119550798838256819273440775635200380478117288464985161
exponent = 65371

powMod_1() --> result:
5445622962585823837922571441457022017266287968814364221835754727821844935853114602997035101447382404175082487869079851706038546152055376156653359681395818988007127255226331370191858002149926005940032029617418888413971859915934084650902231279779736973428693770314916982391992043083339361593785851143510876862384291486366175250142854473033098828509763259270118289017227476791965689610622439182117892457418161901281444262776436423541173630415609298766861209132398807222621987204824334142579836727973280907229614491033564311714521726470513922126372945198576963375743923110660016258773408952750554677023115092140778572708

powMod_2() --> result:
6810714317754472047227163573598062599508233298994055666238011643998914008690111766952492276946449897069119710065677747838443392453981747873097882503496906799568445499162219429711499575125886369304284786317325354188969653127813763063914636326811857776144391033036470082672069543318053031647411624259195488878364092101682829523313581377203766317869506993822432869674329697167373605308085029916745674984464839287705534875663694376921870622058575903956193201537461111459137428055443066661734482468700227988613869537664210332048936320019777161411360781887033415924291408004011076745869838060073534776876143500034757521498

**Comment by shove70** [comment]
> Sorry, do you understand wich part of old iterative powMod was wrong? When I tried to fix it, I didn't find anything wrong with it...
> Maybe it's the BigInt's bug?

It's supposed to be that my code has bugs, not bigint's bugs.

**Comment by Boris-Barboris** [comment]
> It's supposed to be that my code has bugs, not bigint's bugs.

From wikipedia:
```
    base := base mod modulus
    while exponent > 0
        if (exponent mod 2 == 1):
           result := (result * base) mod modulus
        exponent := exponent >> 1
        base := (base * base) mod modulus
```
Your code is different, you need to ```base := base mod modulus``` before the loop, and change to ```base := (base * base) mod modulus```.

**Comment by shove70** [comment]
But it still calculates the wrong result.

```
    static BigInt powMod(BigInt base, BigInt modulus, BigInt exponent)
    {
        assert(base >= 1 && exponent >= 0 && modulus >= 1);

        BigInt result = BigInt("1");
        base = base % modulus;

        while (exponent > 0)
        {
            if (exponent % 2 != 0)
            {
                result = (result * base) % modulus;
            }

            base = (base * base) % modulus;
            exponent /= 2;
        }

        return result;
    }
```

If BigInt has bugs, why does powMod_2 work properly?

**Comment by Boris-Barboris** [comment]
```
static BigInt powMod_2(BigInt base, BigInt modulus, BigInt exponent)
    {
        ...
        BigInt temp = powMod(base, modulus, exponent / 2);
```

Why is recursion into powMod and not into powMod_2?

**Comment by shove70** [comment]
Sorry, I forgot to modify it after copying and pasting.

**Comment by shove70** [comment]
omg, it's really a BigInt's bug.

**Comment by shove70** [comment]
dlang BigInt:
```
import std.stdio;
import std.bigint;

void main(string[] argv)
{
    BigInt a = BigInt("21564064109853809856119436871792921759477602735861860718883598889223231858251567749229246000643946915525172570414005720347114836635107318701077242428657139013586370658636861373800231155999821545535260813976141824");
    BigInt b = BigInt("24803744962281995379823882491100713352172602051429295720009225462760222169497562992822776764893946374887753565629046006562280546321414491579001996466749084176426165385753291715915062443687079028833972893575179478753124157995388126623360442814982987675255286338686337769655739121672376607398141008913866162176");
    BigInt c = BigInt("15592449738095488747095865752434291846961185542216220364759273981537092410281077438681696466616075686558177072453373402338707270142067490009719653528419587472581511984462717336534941668232441962559088176638497609044546648097927645721037778102973426356054296888813806902955798744299849144156358264329743948114764184416762788718214428905372552136684197402848523489807177325912904135652219542981709775375540339611246490836320016382720250825185957794383439798883449063066374895720135846683755238373327764428067892090073454994927125784245547852359595514868496354506574119550798838256819273440775635200380478117288464985161");

    writeln((a * b) % c);
}
```
output:
534869546531112417224433204781062902761898892359096321494237754691434210354537300934260563874019540367943562659323458088415022185792973712551683566996893486557131898263986073285723729647429761218710894708286383629254677810720670377916098070892655931194710549714337100366316289037826643789354059447337922150362505288875800410103474936238316199204856442495452205694882423258214421881355757588835251714670622185442871222378657647830060162105970693118488789207481328313074989530392971574678602770081917482031044573934911488


python:
```
import math

a = 21564064109853809856119436871792921759477602735861860718883598889223231858251567749229246000643946915525172570414005720347114836635107318701077242428657139013586370658636861373800231155999821545535260813976141824
b = 24803744962281995379823882491100713352172602051429295720009225462760222169497562992822776764893946374887753565629046006562280546321414491579001996466749084176426165385753291715915062443687079028833972893575179478753124157995388126623360442814982987675255286338686337769655739121672376607398141008913866162176
c = 15592449738095488747095865752434291846961185542216220364759273981537092410281077438681696466616075686558177072453373402338707270142067490009719653528419587472581511984462717336534941668232441962559088176638497609044546648097927645721037778102973426356054296888813806902955798744299849144156358264329743948114764184416762788718214428905372552136684197402848523489807177325912904135652219542981709775375540339611246490836320016382720250825185957794383439798883449063066374895720135846683755238373327764428067892090073454994927125784245547852359595514868496354506574119550798838256819273440775635200380478117288464985161

print (a * b) % c
```
output:
534869546531112417224433204781062902761898892359096321494237754691434210354537300934260563874019540367943562659323458088415022185792973712551683566996894614987401551960538578949388418152948813112659012433629094338662677449662611596957010904439288232716723045318886779000933601739621574750050993297483196659582404894095318857121844594620014537537456776720985972983385520729044161295299497108549582778848719390446798081923886686452389089223662621089753884338588229458281529170431476597180634550458389509897183526360449024

**Comment by Boris-Barboris** [comment]
Oh, wow! Yeah, to the bugtracker it goes.

**Comment by shove70** [comment]
Okay, it's already submitted:

https://forum.dlang.org/thread/mailman.7533.1552646365.29801.digitalmars-d-bugs@puremagic.com
